// Comprehensive airline code to name mapping (365+ airlines)
export const AIRLINE_NAMES: Record<string, string> = {
  // Major North American
  "AA": "American Airlines",
  "DL": "Delta Air Lines",
  "UA": "United Airlines",
  "WN": "Southwest Airlines",
  "AS": "Alaska Airlines",
  "B6": "JetBlue Airways",
  "NK": "Spirit Airlines",
  "F9": "Frontier Airlines",
  "G4": "Allegiant Air",
  "AC": "Air Canada",
  "WS": "WestJet",
  "AM": "Aeroméxico",
  "Y4": "Volaris",
  "VB": "VivaAerobus",
  "CM": "Copa Airlines",
  
  // European
  "BA": "British Airways",
  "LH": "Lufthansa",
  "AF": "Air France",
  "KL": "KLM Royal Dutch Airlines",
  "IB": "Iberia",
  "AZ": "ITA Airways",
  "LX": "Swiss International Air Lines",
  "OS": "Austrian Airlines",
  "SK": "Scandinavian Airlines",
  "AY": "Finnair",
  "SN": "Brussels Airlines",
  "TP": "TAP Air Portugal",
  "UX": "Air Europa",
  "VY": "Vueling",
  "U2": "easyJet",
  "FR": "Ryanair",
  "W6": "Wizz Air",
  "DS": "easyJet Switzerland",
  "HV": "Transavia",
  "TO": "Transavia France",
  "BE": "Flybe",
  "LS": "Jet2.com",
  "EW": "Eurowings",
  "DE": "Condor",
  "EI": "Aer Lingus",
  "WF": "Widerøe",
  "DY": "Norwegian Air",
  "FI": "Icelandair",
  "PD": "Porter Airlines",
  
  // Middle Eastern
  "EK": "Emirates",
  "QR": "Qatar Airways",
  "EY": "Etihad Airways",
  "WY": "Oman Air",
  "GF": "Gulf Air",
  "SV": "Saudi Arabian Airlines",
  "FZ": "flydubai",
  "XY": "flynas",
  "MS": "EgyptAir",
  "RJ": "Royal Jordanian",
  "LY": "El Al",
  "6H": "Israir",
  "ME": "Middle East Airlines",
  "J9": "Jazeera Airways",
  "KU": "Kuwait Airways",
  
  // Asian
  "SQ": "Singapore Airlines",
  "CX": "Cathay Pacific",
  "JL": "Japan Airlines",
  "NH": "All Nippon Airways",
  "TG": "Thai Airways",
  "MH": "Malaysia Airlines",
  "PR": "Philippine Airlines",
  "VN": "Vietnam Airlines",
  "KE": "Korean Air",
  "OZ": "Asiana Airlines",
  "CI": "China Airlines",
  "BR": "EVA Air",
  "CA": "Air China",
  "MU": "China Eastern Airlines",
  "CZ": "China Southern Airlines",
  "HU": "Hainan Airlines",
  "3U": "Sichuan Airlines",
  "MF": "Xiamen Airlines",
  "HO": "Juneyao Airlines",
  "FM": "Shanghai Airlines",
  "9C": "Spring Airlines",
  "ZH": "Shenzhen Airlines",
  "GA": "Garuda Indonesia",
  "ID": "Batik Air",
  "SJ": "Sriwijaya Air",
  "QZ": "Indonesia AirAsia",
  "TR": "Scoot",
  "3K": "Jetstar Asia",
  "FD": "Thai AirAsia",
  "SL": "Thai Lion Air",
  "DD": "Nok Air",
  "PG": "Bangkok Airways",
  "AK": "AirAsia",
  "D7": "AirAsia X",
  "OD": "Malindo Air",
  "5J": "Cebu Pacific",
  "Z2": "Philippines AirAsia",
  "BL": "Jetstar Pacific",
  "VJ": "VietJet Air",
  "QH": "Bamboo Airways",
  "AI": "Air India",
  "6E": "IndiGo",
  "SG": "SpiceJet",
  "I5": "AirAsia India",
  "G8": "Go First",
  "UK": "Vistara",
  "IX": "Air India Express",
  "PK": "Pakistan International Airlines",
  "BS": "US-Bangla Airlines",
  "BG": "Biman Bangladesh Airlines",
  "RA": "Nepal Airlines",
  "YA": "Yeti Airlines",
  "H9": "Himalaya Airlines",
  "UL": "SriLankan Airlines",
  
  // Turkish
  "TK": "Turkish Airlines",
  "PC": "Pegasus Airlines",
  "XQ": "SunExpress",
  "TI": "AnadoluJet",
  
  // African
  "KQ": "Kenya Airways",
  "ET": "Ethiopian Airlines",
  "SA": "South African Airways",
  "AT": "Royal Air Maroc",
  "WB": "RwandAir",
  "TC": "Air Tanzania",
  "SW": "Air Namibia",
  "BP": "Air Botswana",
  "MK": "Air Mauritius",
  "MD": "Air Madagascar",
  "FP": "Fastjet",
  "UG": "TunisAir",
  "AH": "Air Algérie",
  "U7": "Air Uganda",
  "QU": "Azman Air",
  "W3": "Arik Air",
  "NJ": "Air Senegal",
  "HC": "Air Senegal International",
  "HF": "Air Côte d'Ivoire",
  "8J": "ECAir",
  "GJ": "Ethiopian Cargo",
  
  // Oceania
  "QF": "Qantas",
  "VA": "Virgin Australia",
  "JQ": "Jetstar Airways",
  "TT": "Tigerair Australia",
  "NZ": "Air New Zealand",
  "FJ": "Fiji Airways",
  "PX": "Air Niugini",
  "SB": "Aircalin",
  "VL": "Air VIA",
  "TN": "Air Tahiti Nui",
  
  // South American
  "LA": "LATAM Airlines",
  "JJ": "LATAM Brasil",
  "4M": "LATAM Argentina",
  "UC": "LATAM Chile",
  "LP": "LATAM Peru",
  "XL": "LATAM Ecuador",
  "4C": "LATAM Colombia",
  "G3": "Gol Linhas Aéreas",
  "AD": "Azul Brazilian Airlines",
  "AR": "Aerolineas Argentinas",
  "AV": "Avianca",
  "P5": "Copa Airlines Colombia",
  "VE": "EasyFly",
  "9R": "Satena",
  "PZ": "LATAM Paraguay",
  "OB": "Boliviana de Aviación",
  "Z8": "Amaszonas",
  "2Z": "Amaszonas Uruguay",
  
  // Caribbean
  "BW": "Caribbean Airlines",
  "JY": "InterCaribbean Airways",
  "WG": "Sunwing Airlines",
  "WM": "Windward Islands Airways",
  "3M": "Silver Airways",
  "5Y": "Atlas Air",
  "BB": "Seaborne Airlines",
  "M3": "ABSA Cargo",
  "WQ": "Romavia Air",
  
  // Regional/Charter
  "EV": "ExpressJet",
  "9E": "Endeavor Air",
  "YX": "Midwest Airlines",
  "YV": "Mesa Airlines",
  "OH": "PSA Airlines",
  "OO": "SkyWest Airlines",
  "MQ": "Envoy Air",
  "G7": "GoJet Airlines",
  "C5": "CommutAir",
  "PT": "West Air Sweden",
  "IW": "Wings Air",
  "JV": "Bearskin Airlines",
  "5T": "Canadian North",
  "4N": "Air North",
  "RS": "Air Seoul",
  "LJ": "Jin Air",
  "TW": "T'way Air",
  "7C": "Jeju Air",
  "BX": "Air Busan",
  "RF": "Florida West International Airways",
  "WP": "Island Air",
  "7H": "Ravn Alaska",
  "K5": "SeaPort Airlines",
  "9K": "Cape Air",
  "8N": "Regional Air Services",
  
  // Cargo Airlines
  "5X": "UPS Airlines",
  "FX": "FedEx Express",
  "CK": "Kalitta Air",
  "K4": "Kalitta Charters",
  "KD": "KD Avia",
  "8C": "ATI - Air Transport International",
  "CF": "City Airways",
  "CV": "Cargolux",
  "GT": "Air Guilin",
  "SQ1": "SkyLease Cargo",
  "N8": "National Air Cargo",
  "W8": "Cargojet Airways",
  "LY1": "El Al Cargo",
  "MK1": "Air Mauritius Cargo",
  
  // Business Aviation
  "N5": "Norlandair",
  "RQ": "Kam Air",
  "IF": "Fly Baghdad",
  "XV": "BVI Airways",
  "E9": "Evelop Airlines",
  "2L": "Helvetic Airways",
  "V7": "Volotea",
  "NT": "Binter Canarias",
  "VR": "TACV",
  "L3": "LGW - Luftfahrtgesellschaft Walter",
  "EJ": "New England Airlines",
  "KW": "Wataniya Airways",
  
  // Additional Airlines
  "A3": "Aegean Airlines",
  "JU": "Air Serbia",
  "OU": "Croatia Airlines",
  "OK": "Czech Airlines",
  "LO": "LOT Polish Airlines",
  "RO": "Tarom",
  "FB": "Bulgaria Air",
  "YM": "Montenegro Airlines",
  "JP": "Adria Airways",
  "QS": "SmartWings",
  "WU": "Wizz Air Ukraine",
  "ZB": "Air Albania",
  "V3": "Carpatair",
  "DC": "Braathens Regional Airways",
  "RC": "Atlantic Airways",
  "FT": "Siem Reap Airways",
  "K6": "Cambodia Angkor Air",
  "EN": "Air Dolomiti",
  "AP": "AlbaStar",
  "DW": "Aero Desierto",
  "3J": "Zip Air",
  "HX": "Hong Kong Airlines",
  "KA": "Cathay Dragon",
  "LD": "Air Hong Kong",
  "UO": "Hong Kong Express Airways",
  "9C1": "Spring Airlines Japan",
  "BC": "Skymark Airlines",
  "MM": "Peach Aviation",
  "DJ": "AirAsia Japan",
  "GK": "Jetstar Japan",
  "HD": "Air Do",
  "NU": "Japan Transocean Air",
  "JO": "JALways",
  "EH": "ANA Wings",
  "IJ": "Spring Airlines",
  "BK": "Okay Airways",
  "DR": "Ruili Airlines",
  "JD": "Capital Airlines",
  "PN": "West Air",
  "GS": "Tianjin Airlines",
  "EU": "Chengdu Airlines",
  "NS": "Hebei Airlines",
  "GT1": "Air Guilin",
  "GY": "Colorful Guizhou Airlines",
  "UQ": "Urumqi Air",
  "QW": "Qingdao Airlines",
  "AQ": "9 Air",
  "JR": "Joy Air",
  "RY": "Jiangxi Air",
  "OQ": "Chongqing Airlines",
  "AE": "Mandarin Airlines",
  "GE": "TransAsia Airways",
  "IT": "Tigerair Taiwan",
  "B7": "Uni Air",
  "7G": "StarFlyer",
  "A8": "Aerolink Uganda",
  "QN": "Air Armenia",
  "U8": "Armavia",
  "TL": "Airnorth",
  "BI": "Royal Brunei Airlines",
  "K7": "Air KBZ",
  "YJ": "Asian Wings Airways",
  "IZ": "Arkia",
  "UP": "Bahamasair",
  "LI": "LIAT",
  "ZI": "Aigle Azur",
  "VU": "Air Ivoire",
  "6W": "Saravia",
  "KK": "AtlasGlobal",
  "H4": "HiSky",
  "2T": "True Aviation",
  "5F": "FlyOne",
  "MJ": "Myway Airlines",
  "S4": "SATA Air Açores",
  "NI": "PGA - Portugália Airlines",
  "YW": "Air Nostrum",
  "YQ": "Polet Airlines",
  "SU": "Aeroflot",
  "S7": "S7 Airlines",
  "U6": "Ural Airlines",
  "DP": "Pobeda",
  "FV": "Rossiya Airlines",
  "NN": "VIM Airlines",
  "N4": "Nordwind Airlines",
  "6R": "Alrosa",
  "5N": "Nordavia",
  "R3": "Yakutia Airlines",
  "PS": "Ukraine International Airlines",
  "VV": "Aerosvit Airlines",
  "7B": "Krasavia",
  "2I": "Star Peru",
  "H2": "Sky Airline",
  "LA1": "LATAM Express",
  "4O": "Interjet",
  "VW": "Aeromar",
  "SY": "Sun Country Airlines",
  "XP": "Xtra Airways",
  "Q6": "Volaris Costa Rica",
  "TA": "TACA International Airlines",
  "N3": "Omskavia",
  "5M": "FlyMontserrat",
  
  // Additional Asian carriers
  "9W": "Jet Airways",
  "IT1": "Kingfisher Airlines",
  "IG": "Air Italy",
  "AO": "Australian Airlines",
  "FQ": "Thomas Cook Airlines",
  "MT": "Thomas Cook Airlines",
  "BY": "TUI Airways",
  "TB": "TUI fly Belgium",
  "OR": "TUI fly Netherlands",
  "X3": "TUI fly Germany",
  "6B": "TUIfly Nordic",
  "HZ": "Aurora Airlines",
  "R2": "ORENAIR",
  "YC": "Yamal Airlines",
  "ZF": "Azur Air",
  "NN1": "VIM Airlines",
  "QH1": "Kyrgyzstan Airlines",
  "KC": "Air Astana",
  "DV": "SCAT Airlines",
  "HY": "Uzbekistan Airways",
  "KV": "Kavminvodyavia",
  "T5": "Turkmenistan Airlines",
  "BT": "Air Baltic",
  "9U": "Air Moldova",
  "2R": "VIA Rail Canada",
  "LV": "Albanian Airlines",
  "8Q": "Onur Air",
  "6W1": "Saratov Airlines",
  "HG": "NIKI",
  "E5": "Air Arabia Egypt",
  "G9": "Air Arabia",
  "3O": "Air Arabia Maroc",
  "3L": "Air Arabia Abu Dhabi",
  "NE": "Nesma Airlines",
  "SD": "Sudan Airways",
  "ZS": "Air Arabia Jordan",
  "4Z": "Airlink",
  "8Z": "Wizz Air Hungary",
  "5W": "Wizz Air Abu Dhabi",
  "W9": "Wizz Air UK",
  "W4": "Wizz Air Malta",
  "6E1": "IndiGo Airlines",
  "SG1": "SpiceXpress",
  "I51": "FlyArystan",
  "G81": "Air Go",
  "QG": "Citilink",
  "LV1": "AlbaStar",
};

export function getAirlineName(code: string): string {
  return AIRLINE_NAMES[code] || code;
}

export function getAirlineLogoUrl(code: string): string {
  // Using a reliable airline logo API
  return `https://images.kiwi.com/airlines/64/${code}.png`;
}

// Helper function to get full airport/city name
export function getLocationFullName(iataCode: string, cityName?: string, airportName?: string): string {
  if (airportName && cityName) {
    return `${airportName}, ${cityName}`;
  }
  return cityName || airportName || iataCode;
}