// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://panxglbqfnovnxqohlcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhbnhnbGJxZm5vdm54cW9obGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTk1MDksImV4cCI6MjA3NDYzNTUwOX0.eGV8WXCxl1PRhWyaRqXUAyV84uFlR690StX6h-yjal8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});